name: test_workflow

on:
  workflow_dispatch:

jobs:
  test:
    name: Trigger target repository
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Triggering workflow in target repository"
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/abdelrahmanabdelghany/test_actions_target/dispatches \
          -d '{"event_type":"trigger", "client_payload":{"triggered_by":"test_workflow", "message":"Triggered from source repo"}}'

      - name: Wait before checking workflow status
        run: sleep 15

      - name: Fetch workflow run ID
        id: get_run_id
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          TARGET_RUN_ID=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/abdelrahmanabdelghany/test_actions_target/actions/runs \
            | jq -r '.workflow_runs[] | select(.name=="triggered_workflow") | .id' | head -n 1)

          if [ -z "$TARGET_RUN_ID" ]; then
            echo "No workflow run found for the target repository."
            exit 1
          fi

          echo "Target Workflow Run ID: $TARGET_RUN_ID"
          echo "::set-output name=run_id::$TARGET_RUN_ID"

      - name: Poll workflow run status
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          TARGET_RUN_ID=${{ steps.get_run_id.outputs.run_id }}
          for i in {1..20}; do
            STATUS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/abdelrahmanabdelghany/test_actions_target/actions/runs/$TARGET_RUN_ID \
              | jq -r '.status')

            CONCLUSION=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/abdelrahmanabdelghany/test_actions_target/actions/runs/$TARGET_RUN_ID \
              | jq -r '.conclusion')

            echo "Workflow Status: $STATUS, Conclusion: $CONCLUSION"

            if [ "$STATUS" = "completed" ]; then
              if [ "$CONCLUSION" = "success" ]; then
                echo "Target workflow completed successfully!"
                exit 0
              else
                echo "Target workflow failed or was cancelled."
                exit 1
              fi
            fi

            echo "Workflow still running, checking again in 10 seconds..."
            sleep 10
          done

          echo "Timeout reached while waiting for the target workflow."
          exit 1
